version: "3.8"
services:
  api:
    # image: usr-oliver/nestjs-dockerized 
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    # Mount our host Directory to the docker container
    # Mount (.) current directory to the docker container usr/src/app
    # reflect file changes from host to container
    volumes:
      - .:/usr/src/app
      - /node_modules
    # Run in Debug Mode: npm run start:debug --> Don't forget to start your vscode debugger!
    # Run in dev Mode: npm run start:dev
    command: npm run start:debug

    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 
      DB_DATABASE: app

    ports:
      - 3000:3000
      # debugging port
      - 9229:9229


  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root1
      MYSQL_ALLOW_EMPTY_PASSWORD: true # Set to true for empty password
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 

    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    logging:
      driver: none  # Disable logging for MySQL service

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: 
    logging:
      driver: none  # Disable logging for phpMyAdmin service
  
volumes:
  mysql_data:

